import 'dart:typed_data';

import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../features/auth/presentation/providers/auth_provider.dart';
import '../../features/caregiver/data/models/care_log_model.dart';
import '../../features/caregiver/presentation/providers/caregiver_provider.dart';
import '../../features/patient/data/models/medication_model.dart';

/// Generates a 7-day health summary PDF for an assigned patient and
/// opens the system share/print sheet via [Printing].
class PdfExportService {
  PdfExportService._();

  static final _dateFormat = DateFormat('MMM d, y');
  static final _timeFormat = DateFormat('h:mm a');

  static Future<void> exportHealthSummary({
    required WidgetRef ref,
    required String patientId,
    required String patientName,
  }) async {
    final uid = ref.read(authStateProvider).valueOrNull?.uid ?? '';
    final repo = ref.read(caregiverRepositoryProvider);

    final since = DateTime.now().subtract(const Duration(days: 7));
    final logs = await repo.careLogsForPdf(uid, patientId, since);

    final meds = ref
            .read(assignedPatientMedsProvider(patientId))
            .valueOrNull ??
        [];

    final bytes = await _buildPdf(
      patientName: patientName,
      meds: meds,
      logs: logs,
      since: since,
    );

    await Printing.sharePdf(
      bytes: bytes,
      filename: 'CureSync_${patientName.replaceAll(' ', '_')}_'
          '${DateFormat('yyyyMMdd').format(DateTime.now())}.pdf',
    );
  }

  static Future<Uint8List> _buildPdf({
    required String patientName,
    required List<MedicationModel> meds,
    required List<CareLogModel> logs,
    required DateTime since,
  }) async {
    final doc = pw.Document();

    // ── Fonts ──────────────────────────────────────────────────────────────
    final fontBold = await PdfGoogleFonts.poppinsBold();
    final fontRegular = await PdfGoogleFonts.interRegular();
    final fontSemiBold = await PdfGoogleFonts.interMedium();

    final teal = PdfColor.fromHex('#0D9488');
    final slate = PdfColor.fromHex('#0F172A');
    final muted = PdfColor.fromHex('#94A3B8');
    final surface = PdfColor.fromHex('#F8FBFA');
    final divider = PdfColor.fromHex('#E2E8F0');

    final now = DateTime.now();
    final dateRange =
        '${_dateFormat.format(since)} – ${_dateFormat.format(now)}';

    // ── Page ───────────────────────────────────────────────────────────────
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        header: (_) => _buildHeader(
          patientName: patientName,
          dateRange: dateRange,
          fontBold: fontBold,
          fontRegular: fontRegular,
          teal: teal,
          slate: slate,
          muted: muted,
          surface: surface,
        ),
        footer: (_) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Generated by CureSync',
                style: pw.TextStyle(
                    font: fontRegular,
                    fontSize: 9,
                    color: muted)),
            pw.Text(_dateFormat.format(now),
                style: pw.TextStyle(
                    font: fontRegular, fontSize: 9, color: muted)),
          ],
        ),
        build: (_) => [
          pw.SizedBox(height: 16),

          // ── Active Medications ─────────────────────────────────────────
          _sectionTitle('Active Medications', fontBold, teal),
          pw.SizedBox(height: 8),
          if (meds.isEmpty)
            _emptyRow('No active medications on record', fontRegular, muted)
          else
            ...meds.map((m) => _medRow(m, fontSemiBold, fontRegular, slate, muted, teal, divider)),

          pw.SizedBox(height: 20),

          // ── Care Logs (last 7 days) ────────────────────────────────────
          _sectionTitle('Care Notes — Last 7 Days', fontBold, teal),
          pw.SizedBox(height: 8),
          if (logs.isEmpty)
            _emptyRow('No care logs in this period', fontRegular, muted)
          else
            ...logs.map((l) => _logRow(l, fontSemiBold, fontRegular, slate, muted, divider)),

          pw.SizedBox(height: 20),

          // ── Adherence Summary ──────────────────────────────────────────
          _sectionTitle('Adherence Overview', fontBold, teal),
          pw.SizedBox(height: 8),
          _adherenceSummary(meds, fontRegular, fontSemiBold, slate, muted, teal, surface),
        ],
      ),
    );

    return doc.save();
  }

  // ── Header ─────────────────────────────────────────────────────────────────

  static pw.Widget _buildHeader({
    required String patientName,
    required String dateRange,
    required pw.Font fontBold,
    required pw.Font fontRegular,
    required PdfColor teal,
    required PdfColor slate,
    required PdfColor muted,
    required PdfColor surface,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 16),
      decoration: pw.BoxDecoration(
        border: pw.Border(
            bottom: pw.BorderSide(color: teal, width: 2)),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('CureSync',
                  style: pw.TextStyle(
                      font: fontBold, fontSize: 22, color: teal)),
              pw.Text('7-Day Health Summary',
                  style: pw.TextStyle(
                      font: fontRegular, fontSize: 11, color: muted)),
            ],
          ),
          pw.Spacer(),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(patientName,
                  style: pw.TextStyle(
                      font: fontBold, fontSize: 14, color: slate)),
              pw.Text(dateRange,
                  style: pw.TextStyle(
                      font: fontRegular, fontSize: 10, color: muted)),
            ],
          ),
        ],
      ),
    );
  }

  // ── Section Title ──────────────────────────────────────────────────────────

  static pw.Widget _sectionTitle(
      String title, pw.Font fontBold, PdfColor teal) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#F0FDFA'),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Text(title,
          style: pw.TextStyle(
              font: fontBold, fontSize: 12, color: teal)),
    );
  }

  // ── Medication Row ─────────────────────────────────────────────────────────

  static pw.Widget _medRow(
    MedicationModel m,
    pw.Font fontSemiBold,
    pw.Font fontRegular,
    PdfColor slate,
    PdfColor muted,
    PdfColor teal,
    PdfColor divider,
  ) {
    final times = m.reminderTimes.join(', ');
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 10),
      decoration: pw.BoxDecoration(
        border: pw.Border(
            bottom: pw.BorderSide(color: divider, width: 0.5)),
      ),
      child: pw.Row(
        children: [
          pw.Container(
            width: 6,
            height: 6,
            decoration: pw.BoxDecoration(
              color: teal,
              shape: pw.BoxShape.circle,
            ),
          ),
          pw.SizedBox(width: 10),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(m.name,
                    style: pw.TextStyle(
                        font: fontSemiBold,
                        fontSize: 11,
                        color: slate)),
                pw.Text('${m.dosage}  ·  ${m.durationDays} days',
                    style: pw.TextStyle(
                        font: fontRegular,
                        fontSize: 10,
                        color: muted)),
              ],
            ),
          ),
          pw.Text(times,
              style: pw.TextStyle(
                  font: fontRegular, fontSize: 10, color: muted)),
        ],
      ),
    );
  }

  // ── Care Log Row ───────────────────────────────────────────────────────────

  static pw.Widget _logRow(
    CareLogModel l,
    pw.Font fontSemiBold,
    pw.Font fontRegular,
    PdfColor slate,
    PdfColor muted,
    PdfColor divider,
  ) {
    final typeLabel = switch (l.type) {
      CareLogType.observation => 'Observation',
      CareLogType.medicationNote => 'Medication Note',
      CareLogType.vitalNote => 'Vital Note',
      CareLogType.general => 'General',
    };

    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 10),
      decoration: pw.BoxDecoration(
        border: pw.Border(
            bottom: pw.BorderSide(color: divider, width: 0.5)),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 80,
            child: pw.Text(
              _timeFormat.format(l.createdAt),
              style: pw.TextStyle(
                  font: fontRegular, fontSize: 9, color: muted),
            ),
          ),
          pw.SizedBox(width: 8),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(typeLabel,
                    style: pw.TextStyle(
                        font: fontSemiBold,
                        fontSize: 10,
                        color: slate)),
                pw.SizedBox(height: 2),
                pw.Text(l.note,
                    style: pw.TextStyle(
                        font: fontRegular,
                        fontSize: 10,
                        color: muted)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ── Adherence Summary ──────────────────────────────────────────────────────

  static pw.Widget _adherenceSummary(
    List<MedicationModel> meds,
    pw.Font fontRegular,
    pw.Font fontSemiBold,
    PdfColor slate,
    PdfColor muted,
    PdfColor teal,
    PdfColor surface,
  ) {
    final active = meds.where((m) => m.isActive && !m.isExpired).length;
    final total = meds.length;
    final totalDoses =
        meds.fold<int>(0, (sum, m) => sum + m.reminderTimes.length);

    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: surface,
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: PdfColor.fromHex('#E2E8F0')),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          _statCell('$active / $total', 'Active Meds',
              fontSemiBold, fontRegular, slate, muted),
          _statCell('$totalDoses', 'Daily Doses',
              fontSemiBold, fontRegular, slate, muted),
          _statCell('7', 'Days Covered',
              fontSemiBold, fontRegular, slate, muted),
        ],
      ),
    );
  }

  static pw.Widget _statCell(
    String value,
    String label,
    pw.Font fontSemiBold,
    pw.Font fontRegular,
    PdfColor slate,
    PdfColor muted,
  ) {
    return pw.Column(
      children: [
        pw.Text(value,
            style: pw.TextStyle(
                font: fontSemiBold, fontSize: 18, color: slate)),
        pw.Text(label,
            style: pw.TextStyle(
                font: fontRegular, fontSize: 9, color: muted)),
      ],
    );
  }

  static pw.Widget _emptyRow(
      String text, pw.Font font, PdfColor muted) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 10),
      child: pw.Text(text,
          style: pw.TextStyle(font: font, fontSize: 11, color: muted)),
    );
  }
}
